server:
  port: 8091
  servlet:
    context-path: /bank/v1

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: system
    password: Luna6031561
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
    generate-ddl: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher